---
title: "Data Science"
output:
  html_document:
    toc_float: true
    fig_width: 1
---

These are my notes from "Introduction to Data Science" at Middlebury College (Spring 2020). 

## Class Notes: 

* [Basics](notes/Notes_Basics_Instructor.html)
  * [raw .Rmd ](notes/Notes_Basics_Instructor.Rmd)
* [Transformation  ](notes/Notes_Transformation_Instructor.html)
  * [raw .Rmd file](notes/Notes_Transformation_Instructor.Rmd)
* [Visualization  ](notes/Notes_Visualization_Instructor.html)
  * [raw .Rmd file ](notes/Notes_Visualization_Instructor.rmd)
* [Maps ](notes/Notes_Maps.html)
  * [Maps - Introduction (YouTube Video)](https://youtu.be/ZjZoYdQ9F5M)
  * [Maps - North Carolina (YouTube Video)](https://youtu.be/k-ga1bWzakc)
  * [Maps - Basics of library(rnaturalearth)  (YouTube Video)](https://youtu.be/Fr7UQtvV010)
  * [Maps - library(rnaturalearth) adding points (YouTube Video)](https://youtu.be/wHQYkEdUefQ)
  * [Maps - Basics of using library(maps) (YouTube Video)](https://youtu.be/VjbWRR2JhN0)
  * [Maps - Using Data with library(maps) (YouTube Video)](https://youtu.be/zCaM6wan5hM)
  * [raw .Rmd file](notes/Notes_Maps.Rmd)
* [Web Scraping ](notes/Notes_WebScraping.html)
  * [Web Scraping - Using rvest to scrape data from html tables (YouTube Video)](https://youtu.be/yZVreEX2EnA)
  * [Web Scraping - wprking with scraped data (YouTube Video)](https://youtu.be/bdWzPhNPIFw)
  * [Web Scraping - another example / cleaning web scraped data (YouTube Video)](https://youtu.be/NZnWF4nqblI)
  * [raw .Rmd file](notes/Notes_WebScraping.Rmd)
* [Joins ](notes/Notes_Joins.html)
  * [Joins - Intro (YouTube Video)](https://youtu.be/EJsBqgk2Py8)
  * [Joins - Working with Joined Data (YouTube Video)](https://youtu.be/7C2Ka-LM6ww)
  * [Joins - Types of Joins (YouTube Video)](https://youtu.be/XNb0yjqaP5E)
  * [raw .Rmd file](notes/Notes_Joins.Rmd)
* [Modeling ](notes/Notes_Modeling.html)
  * [Modeling - Intro to "house" dataset (YouTube Video)](https://youtu.be/6DFk4LXqTcA)
  * [Modeling - Intro to Simple Linear Regression (YouTube Video)](https://youtu.be/9fRAiFzOMng)
  * [Modeling - Is this a good model? (YouTube Video)](https://youtu.be/HoUGtqTubfs)
  * [Modeling - Making Predictions (YouTube Video)](https://youtu.be/7OkRsLME_Iw)
  * [Modeling - Multiple Regression (YouTube Video)](https://youtu.be/9ppAxCadfkk)
  * [Modeling - AIC and R Squared (YouTube Video)](https://youtu.be/BuhoxGJCE70)
  * [Modeling - Step Function (YouTube Video)](https://youtu.be/17G12TqRsdM)
  * [Modeling - Intro to "email" dataset (YouTube Video)](https://youtu.be/mAKLp0yLsFE)
  * [Modeling - Intro to Logistic Regression (YouTube Video)](https://youtu.be/GHG-I5R1NAg)
  * [Modeling - Making Predictions with Logistic Regression (YouTube Video)](https://youtu.be/yIH-zgZ1y-k)
  * [raw .Rmd file](notes/Notes_Modeling.rmd)
* [Animation ](notes/Notes_Animation.html)
  * [Animation - Intro (YouTube Video)](https://youtu.be/kL7Ogq5MKh8)
  * [Animation - gganimate "Gapminder" data (YouTube Video)](https://youtu.be/tCGW49nipQY) 
  * [Animation - ease_aes() (YouTube Video)](https://youtu.be/m7MsjJZ_QpI) 
  * [Animation - gganimate "Air Quality" data (YouTube Video)](https://youtu.be/X6J8jh-Gdbs) 
  * [Animation - more examples (YouTube Video)](https://youtu.be/ZQTK3A2xN2o) 
  * [Animation - plotly (YouTube Video)](https://youtu.be/gk5VhST4h_Q) 
  * [raw .Rmd file](notes/Notes_Animation.Rmd)