---
title: "Welcome to my website!"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Set WD and read in data, include = FALSE}

#set your working directory
setwd("C:/Users/nickc/Desktop/Github/nickc/rice-practice-website ")

#Load your libraries
library(readxl)
library(rgdal)
library(raster)
library(spdep)
library(tigris)
library(tidyverse)
library(lubridate)
library(devtools)
#install_github('mcooper/moranfast')
#library(moranfast)
remotes::install_github("rspatial/rspatial")
library(rspatial)
library(latticeExtra)
library(RColorBrewer)
library(spdep)
library(spatialreg)
library(ggplot2)
library(readxl)
library(ggpubr)
library(ggrepel)
library(sf)
install.packages("rnaturalearthdata")
library(rnaturalearth)
devtools::install_github("ropensci/rnaturalearthhires")
library(rnaturalearthhires)

```
Rice is a major staple across the world. One particular region where it is very important is southeast Asia. This data set explores the change in rice yields over time using data from the Food and Agriculture Organization of the United Nations. 

```{r Load in data}
Rice<-read_excel("Rice_yield_FAO.xlsx", sheet = "Sheet1")
str(Rice)
head(Rice)
```

